describe('Adoption form', function() {
    it('successfully loads', function() {
        cy.viewport(1500, 1000)
        cy.visit('http://localhost:3000/adopt')
        cy.contains('Adoption Form')
        cy.get('input[name=firstName]')
            .type('Renee')
            .should('have.value', 'Renee')
        cy.get('input[name=LastName]')
            .type('Nilsen')
            .should('have.value', 'Nilsen')
        cy.get('input[name=contactNumber]')
            .type('0411111111')
            .should('have.value', '0411111111')
        cy.get('input[name=email]')
            .type('abc@def.com')
            .should('have.value', 'abc@def.com')
        cy.get('input[name=addressStreet]')
            .type('123 Rainbow St')
            .should('have.value', '123 Rainbow St')
        cy.get('input[name=addressSuburb]')
            .type('Nowhere')
            .should('have.value', 'Nowhere')
        cy.get('input[name=addressPostcode]')
            .type('1234')
            .should('have.value', '1234')
        cy.get('select').select('Friends or Family')
        cy.contains('Next').click()

        cy.get('select').select('Cat')
        cy.get('input[name=name]')
            .type('Abbey')
            .should('have.value', 'Abbey')
        cy.get('input[name=age]')
            .type('9')
            .should('have.value', '9')
        cy.get('input[name=breed]')
            .type('Domestic Short Hair')
            .should('have.value', 'Domestic Short Hair')
        cy.get('textarea[name=whyAdopt]')
            .type('Companion Animal')
            .should('have.value', 'Companion Animal')
        cy.get('textarea[name=whyThisAnimal]')
            .type('Bonded at event')
            .should('have.value', 'Bonded at event')
        cy.get('textarea[name=desirableCharacteristics]')
            .type('Friendly')
            .should('have.value', 'Friendly')
        cy.get('textarea[name=undesirableCharacteristics]')
            .type('None')
            .should('have.value', 'None')
        cy.contains('Next').click()

        cy.get('select').select('I own my own home')
        cy.get('textarea[name=livingArrangementDayNight]')
            .type('Inside only')
            .should('have.value', 'Inside only')
        cy.get('textarea[name=otherPets]')
            .type('No other pets')
            .should('have.value', 'No other pets')
        cy.get('textarea[name=otherPetsVetwork]')
            .type('NA')
            .should('have.value', 'NA')
        cy.get('textarea[name=otherPeople]')
            .type('Live with my partner, not many guest come over and are mostly adults')
            .should('have.value', 'Live with my partner, not many guest come over and are mostly adults')
        cy.contains('Next').click()


        cy.get('textarea[name=homeAloneHours]')
            .type('Will be alone Mon-Fri 8-6')
            .should('have.value', 'Will be alone Mon-Fri 8-6')
        cy.get('select').select('We would not do any exercise')
        cy.get('textarea[name=holidays]')
            .type('Parents would stay over')
            .should('have.value', 'Parents would stay over')
        cy.contains('Next').click()

        cy.get('textarea[name=surrenderAnAnimal]')
            .type('No')
            .should('have.value', 'No')
        cy.get('textarea[name=refusedAnAnimal]')
            .type('No')
            .should('have.value', 'No')
        cy.get('select').eq(0).select('None of the above - I would be committed to this (Cat or Dog) for life')
        cy.get('select').eq(1).select('No')
        cy.get('select').eq(2).select('Yes')
        cy.get('select').eq(3).select('Yes - I agree to contact Happy Tails Animal Rescue Inc. if I ever need to rehome my (Cat or Dog)')
        cy.get('select').eq(4).select('No')
        cy.contains('Next').click()

        cy.contains('Next').click()
        cy.get('select').select('I agree')
        cy.get('input[name=fullName]')
            .type('Renee Nilsen')
            .should('have.value', 'Renee Nilsen')
        cy.get('input[name=sign]')
            .type('RNilsen')
            .should('have.value', 'RNilsen')
        cy.contains('Submit').click()
    })
})